### ISSUE TITLE
TEMPLATE_DIRS deprecated sience Django 1.8

### ISSUE THREAD

**Issue by Shtucer** [mjbrownie/vim-htmldjango_omnicomplete#10]
I've tried to fix it in `get_template_names()`.

```python
def get_template_names(pattern):
    dirs = mysettings.TEMPLATE_DIRS + app_template_dirs
    if hasattr(mysettings, "TEMPLATES"):
        # For Django 1.8
        for d in [e["DIRS"] for e in mysettings.TEMPLATES]:
            dirs += tuple(d)
```

**Comment by mjbrownie** [comment]
Thanks for that..

 mysettings.TEMPLATE_DIRS 

should be checked with hasattr as well if it is getting depreciated. I'll merge it when I can but if you could make a pull request it would be great.

**Comment by mjbrownie** [comment]
Added in d7f0fe9

**Comment by Shtucer** [comment]
Sorry, I was busy. Note, Django 1.8 has Jinja2 template engine as well as DjangoTemplate. Perhaps this is not important, just to keep in mind.
And finaly, pay attention to previous [issue](https://github.com/mjbrownie/vim-htmldjango_omnicomplete/issues/9).
